Networking\InitCmsBundle\Entity\GalleryHasMedia:
  type: entity
  table: media__gallery_media
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    link:
      type: string
      length: 150
      nullable: true
    caption:
      type: string
      length: 512
      nullable: true